/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.students.enrollmentsystem;

import javax.swing.JFrame;

/**
 *
 * @author Lenovo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAddStudent = new javax.swing.JMenuItem();
        mnuEditStudent = new javax.swing.JMenuItem();
        mnuRemoveStudent = new javax.swing.JMenuItem();
        mnuAddSubject = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuEditSubject = new javax.swing.JMenuItem();
        mnuRemoveSubject = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuAddCourse = new javax.swing.JMenuItem();
        mnuEditCourse = new javax.swing.JMenuItem();
        mnuRemoveCourse = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuEnrollStudent = new javax.swing.JMenuItem();
        mnuUnEnrollStudent = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enrollment System");

        jMenu1.setText("Student");

        mnuAddStudent.setText("Add Student");
        mnuAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddStudentActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAddStudent);

        mnuEditStudent.setText("Edit Student");
        mnuEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditStudentActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEditStudent);

        mnuRemoveStudent.setText("Remove Student");
        mnuRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRemoveStudentActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRemoveStudent);

        jMenuBar1.add(jMenu1);

        mnuAddSubject.setText("Subject");

        jMenuItem3.setText("Add Subject");
        mnuAddSubject.add(jMenuItem3);

        mnuEditSubject.setText("Edit Subject");
        mnuAddSubject.add(mnuEditSubject);

        mnuRemoveSubject.setText("Remove Subject");
        mnuAddSubject.add(mnuRemoveSubject);

        jMenuBar1.add(mnuAddSubject);

        jMenu3.setText("Course");

        mnuAddCourse.setText("Add Course");
        jMenu3.add(mnuAddCourse);

        mnuEditCourse.setText("Edit Course");
        jMenu3.add(mnuEditCourse);

        mnuRemoveCourse.setText("Remove Course");
        jMenu3.add(mnuRemoveCourse);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Enrollment ");

        mnuEnrollStudent.setText("Enroll Student");
        jMenu4.add(mnuEnrollStudent);

        mnuUnEnrollStudent.setText("UnEnroll Student");
        jMenu4.add(mnuUnEnrollStudent);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddStudentActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Student();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Add Student");
        frame.setVisible(true);
    }//GEN-LAST:event_mnuAddStudentActionPerformed

    private void mnuEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditStudentActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Student();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Edit Student");
        frame.setVisible(true);
    }//GEN-LAST:event_mnuEditStudentActionPerformed

    private void mnuRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRemoveStudentActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Student();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Remove Student");
        frame.setVisible(true);
    }//GEN-LAST:event_mnuRemoveStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /* java.awt.EventQueue.invokeLater(() -> {
            JFrame frame = new Main();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mnuAddCourse;
    private javax.swing.JMenuItem mnuAddStudent;
    private javax.swing.JMenu mnuAddSubject;
    private javax.swing.JMenuItem mnuEditCourse;
    private javax.swing.JMenuItem mnuEditStudent;
    private javax.swing.JMenuItem mnuEditSubject;
    private javax.swing.JMenuItem mnuEnrollStudent;
    private javax.swing.JMenuItem mnuRemoveCourse;
    private javax.swing.JMenuItem mnuRemoveStudent;
    private javax.swing.JMenuItem mnuRemoveSubject;
    private javax.swing.JMenuItem mnuUnEnrollStudent;
    // End of variables declaration//GEN-END:variables
}
