/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.students.enrollmentsystem;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Lenovo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
//        try {
//            this.setContentPane( ImageIO.read(new File("psaubackground.jpg")));
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
        JLabel background=new JLabel(new ImageIcon("C:\\Users\\Lenovo\\Desktop\\NetBeansProjects\\EnrollmentSystem\\src\\main\\java\\com\\students\\enrollmentsystem\\psaubackground.jpg"));
       this.add(background);
//       pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAddStudent = new javax.swing.JMenuItem();
        mnuEditStudent = new javax.swing.JMenuItem();
        mnuRemoveStudent = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuAddSubject = new javax.swing.JMenuItem();
        mnuEditSubject = new javax.swing.JMenuItem();
        mnuRemoveSubject = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuAddSchedule = new javax.swing.JMenuItem();
        mnuEditSchedule = new javax.swing.JMenuItem();
        mnuRemoveSchedule = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuEnrollStudent = new javax.swing.JMenuItem();
        mnuUnEnrollStudent = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enrollment System");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.green);

        jMenu1.setText("Student");

        mnuAddStudent.setText("Add Student");
        mnuAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddStudentActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAddStudent);

        mnuEditStudent.setText("Edit Student");
        mnuEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditStudentActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEditStudent);

        mnuRemoveStudent.setText("Remove Student");
        mnuRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRemoveStudentActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRemoveStudent);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Subject");

        mnuAddSubject.setText("Add Subject");
        mnuAddSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddSubjectActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAddSubject);

        mnuEditSubject.setText("Edit Subject");
        mnuEditSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditSubjectActionPerformed(evt);
            }
        });
        jMenu2.add(mnuEditSubject);

        mnuRemoveSubject.setText("Remove Subject");
        mnuRemoveSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRemoveSubjectActionPerformed(evt);
            }
        });
        jMenu2.add(mnuRemoveSubject);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Schedule");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        mnuAddSchedule.setText("Add Schedule");
        mnuAddSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddScheduleActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAddSchedule);

        mnuEditSchedule.setText("Edit Schedule");
        mnuEditSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditScheduleActionPerformed(evt);
            }
        });
        jMenu3.add(mnuEditSchedule);

        mnuRemoveSchedule.setText("Remove Schedule");
        mnuRemoveSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRemoveScheduleActionPerformed(evt);
            }
        });
        jMenu3.add(mnuRemoveSchedule);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Enrollment ");

        mnuEnrollStudent.setText("Enroll Student");
        mnuEnrollStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEnrollStudentActionPerformed(evt);
            }
        });
        jMenu4.add(mnuEnrollStudent);

        mnuUnEnrollStudent.setText("UnEnroll Student");
        mnuUnEnrollStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUnEnrollStudentActionPerformed(evt);
            }
        });
        jMenu4.add(mnuUnEnrollStudent);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddStudentActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Student();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Add Student");
        frame.setVisible(true);
    }//GEN-LAST:event_mnuAddStudentActionPerformed

    private void mnuEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditStudentActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Student();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Edit Student");
        frame.setVisible(true);
    }//GEN-LAST:event_mnuEditStudentActionPerformed

    private void mnuRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRemoveStudentActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Student();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Remove Student");
        frame.setVisible(true);
    }//GEN-LAST:event_mnuRemoveStudentActionPerformed

    private void mnuAddSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddSubjectActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Subject();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Add Subject");
        frame.setVisible(true);
    }//GEN-LAST:event_mnuAddSubjectActionPerformed

    private void mnuEditSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditSubjectActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Subject();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Edit Subject");
        frame.setVisible(true);
    }//GEN-LAST:event_mnuEditSubjectActionPerformed

    private void mnuRemoveSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRemoveSubjectActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Subject();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Remove Subject");
        frame.setVisible(true);

    }//GEN-LAST:event_mnuRemoveSubjectActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void mnuAddScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddScheduleActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Schedule();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Add Schedule");
        frame.setVisible(true);

    }//GEN-LAST:event_mnuAddScheduleActionPerformed

    private void mnuEditScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditScheduleActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Schedule();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Edit Schedule");
        frame.setVisible(true);

    }//GEN-LAST:event_mnuEditScheduleActionPerformed

    private void mnuRemoveScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRemoveScheduleActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Schedule();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Remove Schedule");
        frame.setVisible(true);


    }//GEN-LAST:event_mnuRemoveScheduleActionPerformed

    private void mnuEnrollStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEnrollStudentActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Enrollment();
        frame.setLocationRelativeTo(null);
        frame.setTitle("Enroll Student");
        
        frame.getContentPane().setBackground(Color.LIGHT_GRAY);
        
        frame.setVisible(true);
    }//GEN-LAST:event_mnuEnrollStudentActionPerformed

    private void mnuUnEnrollStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUnEnrollStudentActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Enrollment();
        frame.setLocationRelativeTo(null);
        frame.setTitle("UnEnroll Student");
        frame.setVisible(true);        
    }//GEN-LAST:event_mnuUnEnrollStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /* java.awt.EventQueue.invokeLater(() -> {
            JFrame frame = new Main();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAddSchedule;
    private javax.swing.JMenuItem mnuAddStudent;
    private javax.swing.JMenuItem mnuAddSubject;
    private javax.swing.JMenuItem mnuEditSchedule;
    private javax.swing.JMenuItem mnuEditStudent;
    private javax.swing.JMenuItem mnuEditSubject;
    private javax.swing.JMenuItem mnuEnrollStudent;
    private javax.swing.JMenuItem mnuRemoveSchedule;
    private javax.swing.JMenuItem mnuRemoveStudent;
    private javax.swing.JMenuItem mnuRemoveSubject;
    private javax.swing.JMenuItem mnuUnEnrollStudent;
    // End of variables declaration//GEN-END:variables
}
