/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.students.enrollmentsystem;

import com.mongodb.client.MongoDatabase;
import org.bson.Document;
import com.mongodb.MongoClient;
import com.mongodb.client.model.Filters;
import static com.mongodb.client.model.Filters.eq;
import com.mongodb.client.model.Updates;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import org.bson.conversions.Bson;

/**
 *
 * @author Lenovo
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    //Creating a MongoDB client
    MongoClient mongo;
    //Connecting to the database
    MongoDatabase database;

    public Student() {
        initComponents();

        //Creating a MongoDB client
        mongo = new MongoClient("localhost", 27017);
        //Connecting to the database
        database = mongo.getDatabase("db1");

        //Creating a collection
        database.createCollection("Students");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGender = new javax.swing.ButtonGroup();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        txtFullname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBday = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        rbnFemale = new javax.swing.JRadioButton();
        rbnMale = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel1.setText("StudentId:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, -1, -1));

        jLabel2.setText("Full Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 55, -1, -1));

        txtStudentId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStudentIdKeyPressed(evt);
            }
        });
        getContentPane().add(txtStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 12, 96, -1));
        getContentPane().add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 52, 320, -1));

        jLabel8.setText("Birthday:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 59, -1));

        txtBday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBdayFocusLost(evt);
            }
        });
        getContentPane().add(txtBday, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 86, -1));

        jLabel4.setText("Age:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        txtAge.setEditable(false);
        txtAge.setBackground(java.awt.SystemColor.text);
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 76, -1));

        btgGender.add(rbnFemale);
        rbnFemale.setText("Female");
        rbnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(rbnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        btgGender.add(rbnMale);
        rbnMale.setText("Male");
        getContentPane().add(rbnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel3.setText("Gender:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setText("Address:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 320, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    public int getDifferenceDays(LocalDate d1, LocalDate d2) {
        int diff = d1.getYear() - d2.getYear();
        return diff;
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        //Preparing a document
        Document document = new Document();

        String fullname = txtFullname.getText();

        String studid = txtStudentId.getText();
        String birthday = txtBday.getText();
        String age = txtAge.getText();
        String address = txtAddress.getText();
        String gender;
        if (rbnMale.isSelected()) {
            gender = "M";
        } else {
            gender = "F";
        }
        if (this.getTitle().compareTo("Add Student") == 0) {
            document.append("studid", studid);

            document.append("fullname", fullname);
            document.append("birthday", birthday);
            document.append("address", address);
            document.append("age", age);
            document.append("gender", gender);

            database.getCollection("students").insertOne(document);
        } else if (this.getTitle().compareTo("Edit Student") == 0) {
            Bson updates = Updates.combine(
                    Updates.set("fullname",fullname),
                    Updates.set("address",address),
                    Updates.set("address", address),
                    Updates.set("birtday", birthday),
                    Updates.set("age", age),
                    Updates.set("gender", gender)
            );
            database.getCollection("students").updateOne(Filters.eq("studid", studid), updates);
        } else if (this.getTitle().compareTo("Remove Student") == 0) {
            database.getCollection("students").deleteOne( Filters.eq("studid", studid) );
        }

        JOptionPane.showMessageDialog(null, "Student record saved");

        this.dispose();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void rbnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnFemaleActionPerformed

    private void txtBdayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBdayFocusLost
        // TODO add your handling code here:
        ZoneId z = ZoneId.of("Asia/Manila");
        LocalDate today = LocalDate.now(z);  // Always pass a time zone.

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("M/d/y", Locale.ENGLISH);
        LocalDate date = LocalDate.parse(txtBday.getText(), formatter);

        int age = getDifferenceDays(today, date);

        txtAge.setText(String.valueOf(age));
    }//GEN-LAST:event_txtBdayFocusLost

    private void txtStudentIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudentIdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {  //ENTER
            if (this.getTitle().compareTo("Edit Student") == 0 || 
                 this.getTitle().compareTo("Remove Student") == 0 ) {
                Document doc = database.getCollection("students").find(eq("studid", txtStudentId.getText())).first();
                txtFullname.setText(doc.get("fullname").toString());
                txtBday.setText(doc.get("birthday").toString());
                txtAge.setText(doc.get("age").toString());
                txtAddress.setText(doc.get("address").toString());
                if(doc.get("gender").toString().equals("M")){
                    rbnMale.setSelected(true);
                }
                else {
                    rbnFemale.setSelected(true);
                }
            }
        }
    }//GEN-LAST:event_txtStudentIdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgGender;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rbnFemale;
    private javax.swing.JRadioButton rbnMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBday;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}
